import React, { useMemo } from 'react';
import { useUserStore } from '../../store/userStore';
import { AppStage, CurriculumModule } from '../../types';
import BuddyWidget from '../buddy/BuddyWidget';
import { speakBuddyText } from '../../services/geminiService';

// Helper functions to reduce nested ternaries
const getModuleCardClassName = (isCompleted: boolean, isActive: boolean, isLocked: boolean, branch: string) => {
  if (isCompleted) {
    return 'border-green-400 bg-gradient-to-br from-green-50 to-emerald-50 shadow-md';
  }
  if (isActive) {
    const glowColor = getBranchGlowColor(branch);
    return `border-amber-400 bg-gradient-to-br from-amber-50 to-yellow-50 shadow-xl ${glowColor} shadow-lg scale-105`;
  }
  if (isLocked) {
    return 'border-slate-200 bg-slate-50 opacity-60';
  }
  return 'border-purple-200 bg-white shadow-md hover:shadow-lg hover:scale-102';
};

const getModuleIconClassName = (isCompleted: boolean, isActive: boolean) => {
  if (isCompleted) {
    return 'bg-green-100 border-2 border-green-300';
  }
  if (isActive) {
    return 'bg-amber-50 border-2 border-amber-300';
  }
  return 'bg-white border border-slate-200';
};

const getModuleTitleClassName = (isCompleted: boolean, isActive: boolean) => {
  if (isCompleted) {
    return 'text-green-800';
  }
  if (isActive) {
    return 'text-amber-900';
  }
  return 'text-slate-700';
};

const getBranchGlowColor = (branch: string) => {
  if (branch === 'EarlyChildhood') return 'shadow-green-200';
  if (branch === 'SchoolAge') return 'shadow-amber-200';
  if (branch === 'Adolescent') return 'shadow-blue-200';
  return 'shadow-purple-200';
};

const CurriculumBuilder: React.FC = () => {
  const {
    curriculum,
    setStage,
    completedModuleIds,
    moduleContents,
    setActiveModule
  } = useUserStore();

  // Safe access
  const schedule = curriculum?.weeklySchedule || [];

  // Calculate the first active module (not completed and has content)
  // IMPORTANT: This must be before any conditional returns to maintain Hook order
  const activeModule = useMemo(() => {
    if (!curriculum) return null;

    for (const day of schedule) {
      for (const mod of day.modules || []) {
        if (!completedModuleIds.includes(mod.id) && moduleContents[mod.id]) {
          return mod.id;
        }
      }
    }
    return null;
  }, [curriculum, schedule, completedModuleIds, moduleContents]); // Added moduleContents to deps

  // If curriculum is not yet generated by the worker, show a planning screen
  if (!curriculum) {
    return (
      <div className="min-h-screen bg-indigo-900 text-white flex flex-col items-center justify-center space-y-8 p-6 text-center relative overflow-hidden">

        {/* Animated Background */}
        <div className="absolute inset-0 z-0">
          <div className="absolute top-10 left-10 w-64 h-64 bg-purple-600 rounded-full blur-[100px] opacity-30 animate-pulse"></div>
          <div className="absolute bottom-10 right-10 w-64 h-64 bg-blue-600 rounded-full blur-[100px] opacity-30 animate-pulse delay-700"></div>
        </div>

        <div className="z-10 flex flex-col items-center max-w-lg w-full">
          <div className="text-8xl animate-bounce mb-8">🗺️</div>
          <h2 className="text-3xl font-bold mb-4 animate-fade-in">Planning Your Adventure...</h2>
          <p className="text-indigo-200 text-lg mb-8 font-medium">
            Designing a special map just for you!
          </p>

          <div className="w-64 bg-indigo-950 rounded-full h-2 overflow-hidden relative">
            <div className="absolute inset-0 bg-gradient-to-r from-cyan-400 to-blue-500 w-1/2 h-full animate-progress-indeterminate"></div>
          </div>

          <style>{`
                 @keyframes progress-indeterminate {
                    0% { left: -50%; }
                    100% { left: 100%; }
                 }
                 .animate-progress-indeterminate { animation: progress-indeterminate 1.5s infinite linear; }
            `}</style>
        </div>
      </div>
    );
  }

  // READY STATE - SHOW CURRICULUM

  const getBranchColor = (branch: string) => {
    switch (branch) {
      case 'EarlyChildhood': return 'bg-green-500';
      case 'SchoolAge': return 'bg-amber-500';
      case 'Adolescent': return 'bg-blue-600';
      default: return 'bg-indigo-600';
    }
  };

  const getBranchGlowColor = (branch: string) => {
    switch (branch) {
      case 'EarlyChildhood': return 'shadow-green-400';
      case 'SchoolAge': return 'shadow-amber-400';
      case 'Adolescent': return 'shadow-blue-400';
      default: return 'shadow-indigo-400';
    }
  };

  const getModuleBadge = (type: string) => {
    switch (type) {
      case 'PECS': return 'bg-purple-100 text-purple-700';
      case 'SOCIAL_SIM': return 'bg-blue-100 text-blue-700';
      case 'SAFETY_SIGNS': return 'bg-red-100 text-red-700';
      case 'PHONICS': return 'bg-orange-100 text-orange-700';
      case 'I_SPY': return 'bg-pink-100 text-pink-700';
      case 'MEAL_PREP': return 'bg-green-100 text-green-700';
      case 'MONEY': return 'bg-yellow-100 text-yellow-700';
      case 'SOCIAL_STORY': return 'bg-cyan-100 text-cyan-700';
      case 'OFFLINE_TASK': return 'bg-indigo-100 text-indigo-700';
      default: return 'bg-slate-100 text-slate-700';
    }
  };

  const getModuleIcon = (type: string) => {
    switch (type) {
      case 'PECS': return '💬';
      case 'SOCIAL_SIM': return '🤝';
      case 'SAFETY_SIGNS': return '🚸';
      case 'PHONICS': return '🗣️';
      case 'I_SPY': return '🔍';
      case 'MEAL_PREP': return '🍳';
      case 'MONEY': return '💰';
      case 'SOCIAL_STORY': return '📖';
      case 'OFFLINE_TASK': return '🖼️';
      default: return '✨';
    }
  };

  // Calculate day progress
  const getDayProgress = (dayModules: CurriculumModule[]) => {
    const total = dayModules.length;
    const completed = dayModules.filter(m => completedModuleIds.includes(m.id)).length;
    return { completed, total, percentage: total > 0 ? (completed / total) * 100 : 0 };
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 flex flex-col items-center p-6 relative overflow-hidden">

      {/* Background Decorations - Space/Adventure Theme */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        {/* Planets */}
        <div className="absolute top-20 right-10 w-32 h-32 rounded-full bg-gradient-to-br from-purple-300 to-pink-300 opacity-5"></div>
        <div className="absolute bottom-40 left-20 w-40 h-40 rounded-full bg-gradient-to-br from-blue-300 to-cyan-300 opacity-5"></div>
        <div className="absolute top-1/2 right-1/3 w-24 h-24 rounded-full bg-gradient-to-br from-amber-300 to-orange-300 opacity-5"></div>

        {/* Stars */}
        {[...Array(15)].map((_, i) => (
          <div
            key={i}
            className="absolute text-yellow-300 opacity-10"
            style={{
              /* eslint-disable sonarjs/pseudo-random */
              top: `${Math.random() * 100}%`,
              left: `${Math.random() * 100}%`,
              fontSize: `${Math.random() * 20 + 10}px`,
              /* eslint-enable sonarjs/pseudo-random */
            }}
          >
            ✨
          </div>
        ))}
      </div>

      {/* Buddy Widget - will be repositioned near active module */}
      <BuddyWidget context={
        activeModule && !moduleContents[activeModule]
          ? "I am currently building your next mission! It will be ready very soon. You can look at your map while I work!"
          : "Here is your adventure map! Click the big button to start!"
      } />

      <div className="w-full max-w-3xl relative z-10">
        {/* Header with Home Button */}
        <header className="mb-6 flex justify-between items-center">
          <h1 className="text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600">
            🗺️ Adventure Map
          </h1>
          <button
            onClick={() => setStage(AppStage.DASHBOARD)}
            className="flex items-center space-x-2 bg-white hover:bg-slate-50 px-4 py-2 rounded-xl shadow-md border-2 border-slate-200 transition-all hover:scale-105"
          >
            <span className="text-2xl">🏠</span>
            <span className="font-bold text-slate-700">Home</span>
          </button>
        </header>


        <div className="bg-white/80 backdrop-blur-sm rounded-3xl shadow-2xl overflow-hidden mb-8 border-2 border-purple-100">
          <div className={`${getBranchColor(curriculum.branch)} p-6 text-white flex items-center space-x-4 relative overflow-hidden`}>
            {/* Decorative elements */}
            <div className="absolute -right-10 -top-10 w-40 h-40 bg-white/10 rounded-full blur-2xl"></div>
            <div>
              <h2 className="text-2xl font-bold drop-shadow-lg">⚡ {curriculum.branchTitle}</h2>
              <p className="opacity-90 text-sm mt-1">Mission: <span className="font-bold">{curriculum.theme}</span></p>
              <p className="opacity-70 text-xs mt-1">🎨 Visual Style: {(schedule[0]?.modules || [])[0]?.visualStyle || 'Cartoon'}</p>
            </div>
          </div>

          <div className="p-8 relative">
            {schedule.map((day, dayIdx) => {
              const dayProgress = getDayProgress(day.modules || []);
              const isDayCompleted = dayProgress.completed === dayProgress.total;

              return (
                <div key={dayIdx} className="mb-10 last:mb-0 relative">
                  {/* Simple Dashed Path Connection */}
                  {dayIdx < schedule.length - 1 && (
                    <div
                      className="absolute left-[18px] top-12 w-0.5 z-0"
                      style={{
                        height: 'calc(100% + 16px)',
                        backgroundImage: isDayCompleted
                          ? 'repeating-linear-gradient(to bottom, #22c55e 0px, #22c55e 8px, transparent 8px, transparent 16px)'
                          : 'repeating-linear-gradient(to bottom, #cbd5e1 0px, #cbd5e1 8px, transparent 8px, transparent 16px)'
                      }}
                    />
                  )}

                  <div className="flex items-center space-x-3 mb-4 relative z-10">
                    <div className={`w-10 h-10 rounded-full flex items-center justify-center font-black text-white text-lg shadow-md ${isDayCompleted ? 'bg-green-500' : getBranchColor(curriculum.branch)}`}>
                      {isDayCompleted ? '✓' : dayIdx + 1}
                    </div>
                    <h3 className="font-black text-slate-800 text-xl uppercase tracking-tight">{day.day}</h3>
                  </div>

                  <div className="space-y-4 pl-14">
                    {(day.modules || []).map((mod) => {
                      const isCompleted = completedModuleIds.includes(mod.id);
                      const hasContent = !!moduleContents[mod.id];
                      const isActive = mod.id === activeModule;
                      const isLocked = !hasContent;

                      return (
                        <div
                          key={mod.id}
                          className={`
                            relative rounded-2xl border-2 transition-all duration-300 overflow-hidden
                            ${getModuleCardClassName(isCompleted, isActive, isLocked, curriculum.branch)}
                          `}
                        >
                          {/* Glow effect for active card */}
                          {isActive && (
                            <div className="absolute inset-0 bg-gradient-to-r from-amber-200/30 via-yellow-200/30 to-amber-200/30 animate-pulse"></div>
                          )}

                          <div className="relative p-4 flex items-center">
                            {/* Module Icon */}
                            <div className={`
                              w-12 h-12 rounded-xl shadow-sm flex items-center justify-center text-2xl mr-4 flex-shrink-0 relative
                              ${getModuleIconClassName(isCompleted, isActive)}
                            `}>
                              {mod.icon}
                              {/* Completed checkmark */}
                              {isCompleted && (
                                <div className="absolute -top-1 -right-1 bg-green-500 w-5 h-5 rounded-full flex items-center justify-center text-white text-xs">✓</div>
                              )}
                              {/* Locked indicator */}
                              {isLocked && (
                                <div className="absolute -top-1 -right-1 bg-slate-400 w-5 h-5 rounded-full flex items-center justify-center text-white text-xs">🔒</div>
                              )}
                            </div>

                            {/* Module Info */}
                            <div className="flex-1 min-w-0 mr-4">
                              <div className="flex items-center space-x-2 mb-2 flex-wrap">
                                <h4 className={`font-bold text-base ${getModuleTitleClassName(isCompleted, isActive)}`}>
                                  {mod.title}
                                </h4>
                                {/* Module Type with Icon */}
                                <span className={`text-xs px-2 py-1 rounded-full font-bold flex items-center space-x-1 ${getModuleBadge(mod.type)}`}>
                                  <span>{getModuleIcon(mod.type)}</span>
                                  <span>{mod.type === 'OFFLINE_TASK' ? 'GUESS PICTURE' : mod.type.replace('_', ' ')}</span>
                                </span>
                              </div>
                              <p className="text-sm text-slate-600">{mod.description}</p>
                              <div className="flex items-center space-x-3 mt-2">
                                <span className="text-xs text-slate-500 font-medium">⏱️ {mod.durationMinutes} min</span>
                                {isCompleted && <span className="text-xs text-green-600 font-bold">✓ Completed!</span>}
                                {isLocked && !hasContent && <span className="text-xs text-slate-500 font-medium">🔒 Preparing...</span>}
                                {isActive && hasContent && (
                                  <span className="text-xs text-amber-600 font-bold animate-pulse">
                                    ✨ {moduleContents[mod.id]?.questions?.length || 1} questions ready!
                                  </span>
                                )}
                              </div>
                            </div>

                            {/* PLAY Button for Active Module */}
                            {isActive && !isCompleted && (
                              <button
                                onClick={() => {
                                  if (!hasContent) {
                                    speakBuddyText(`Hold on! I'm still building the ${mod.title} mission. The first question should be ready very soon!`);
                                    return;
                                  }
                                  setActiveModule(mod);
                                  setStage(AppStage.GAME_ARENA);
                                }}
                                className={`
                                  px-6 py-3 rounded-xl font-black text-white text-lg shadow-lg
                                  transform transition-all 
                                  ${hasContent
                                    ? `${getBranchColor(curriculum.branch)} hover:scale-110 active:scale-95 animate-bounce`
                                    : 'bg-slate-400 cursor-not-allowed opacity-75'}
                                  flex items-center space-x-2
                                `}
                              >
                                {hasContent ? (
                                  <>
                                    <span>▶️</span>
                                    <span>PLAY</span>
                                  </>
                                ) : (
                                  <>
                                    <span className="animate-spin">⚙️</span>
                                    <span className="text-sm">Building...</span>
                                  </>
                                )}
                              </button>
                            )}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Start Adventure Button */}
        <button
          onClick={() => {
            // Find first active module from the computed activeModule state
            if (activeModule) {
              const foundModule = schedule
                .flatMap(day => day.modules || [])
                .find(m => m.id === activeModule);

              // eslint-disable-next-line no-console
              console.log('[CurriculumBuilder] Start clicked:', {
                activeModule,
                foundModule: foundModule?.id,
                hasContent: foundModule ? !!moduleContents[foundModule.id] : false,
                contentKeys: Object.keys(moduleContents)
              });

              // Only proceed if module exists and has content
              if (foundModule && moduleContents[foundModule.id]) {
                setActiveModule(foundModule);
                setStage(AppStage.GAME_ARENA);
              } else {
                speakBuddyText(`I'm still preparing your mission! The first question should be ready in just a few seconds. You can see the progress on the map!`);
              }
            } else {
              // eslint-disable-next-line no-console
              console.log('[CurriculumBuilder] No active module found. Content status:', Object.keys(moduleContents));
              speakBuddyText(`I'm still building your adventure map! Give me a moment!`);
            }
          }}
          className={`
            w-full py-5 text-white rounded-2xl text-2xl font-black shadow-2xl 
            transition-all duration-300 
            flex items-center justify-center space-x-3
            ${activeModule && moduleContents[activeModule]
              ? `${getBranchColor(curriculum.branch)} ${getBranchGlowColor(curriculum.branch)} hover:scale-105 active:scale-95 animate-pulse hover:animate-none`
              : 'bg-slate-400 cursor-not-allowed opacity-80'}
          `}
        >
          {activeModule && moduleContents[activeModule] ? (
            <>
              <span className="text-3xl">🚀</span>
              <span>Start Adventure!</span>
              <span className="text-3xl">🚀</span>
            </>
          ) : (
            <>
              <span className="text-3xl animate-spin">⚙️</span>
              <span>Preparing Mission...</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
};

export default CurriculumBuilder;
